language: R

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - libcurl4-openssl-dev

repos:
  CRAN: "https://cran.rstudio.org"
  ropensci: "https://packages.ropensci.org"

cache: packages

before_install:
  - cat ~/.Rprofile
  - Rscript -e 'options("repos")'
  #- chmod u+x setup.sh;./setup.sh
  #- export PATH=$HOME/R-bin/bin:$PATH
  #- export LD_LIBRARY_PATH=$HOME/R-bin/lib:$LD_LIBRARY_PATH
  #- Rscript -e 'sessionInfo()'
  - echo "$_R_CHECK_CRAN_INCOMING_"
  - echo "$TRAVIS_PULL_REQUEST"
  - echo "$TRAVIS_REPO_SLUG"
